Add appendFilter list
wcm-io-devops/conga-aem-definitions pull request #83
Opened 2022-11-22 13:50 UTC by tobias-richter

Add a new `appendFilter` list in order to apply deny rules at the very end of the filter list.
This avoids deny rules to be bypassed by other filters.

2022-12-05 16:05 UTC, stefanseifert requested changes

2023-01-02 13:06 UTC, tobias-richter commented on conga-aem-definitions/src/main/roles/aem-dispatcher.yaml
> +      appendFilter:
@stefanseifert renamed the list to filterAppend.

2023-01-02 13:06 UTC, tobias-richter commented on conga-aem-definitions/src/main/templates/aem-dispatcher/publish/dispatcher_publish.any.hbs
> +      /999{{@index}}
@stefanseifert i have changed this to the prefix `append_`

2023-01-03 09:22 UTC, stefanseifert approved these changes

2023-01-03 09:23 UTC, merged